// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Killin-IT_TEST

#include "../ui.h"

void ui_Active_Screen_screen_init(void)
{
ui_Active_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Active_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Active_Arc = lv_arc_create(ui_Active_Screen);
lv_obj_set_width( ui_Active_Arc, 240);
lv_obj_set_height( ui_Active_Arc, 240);
lv_obj_set_align( ui_Active_Arc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Active_Arc, 1);
lv_arc_set_bg_angles(ui_Active_Arc,150,30);
lv_obj_set_style_arc_color(ui_Active_Arc, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Active_Arc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Active_Arc, 24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Active_Arc, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Active_Arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Active_Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Active_Arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Active = lv_label_create(ui_Active_Screen);
lv_obj_set_width( ui_Active, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Active, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Active, -1 );
lv_obj_set_y( ui_Active, 70 );
lv_obj_set_align( ui_Active, LV_ALIGN_CENTER );
lv_label_set_text(ui_Active,"ACTIVE");
lv_obj_set_style_text_color(ui_Active, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Active, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Active, &ui_font_Designer, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Active_Screen);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -1 );
lv_obj_set_y( ui_Label1, -20 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"KILLIN'-IT");
lv_obj_set_style_text_font(ui_Label1, &ui_font_Akira_Extended, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Active_Screen);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -1 );
lv_obj_set_y( ui_Label5, 10 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"E-STOP SYSTEM");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CSD2 = lv_label_create(ui_Active_Screen);
lv_obj_set_width( ui_CSD2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CSD2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CSD2, 0 );
lv_obj_set_y( ui_CSD2, 110 );
lv_obj_set_align( ui_CSD2, LV_ALIGN_CENTER );
lv_label_set_text(ui_CSD2,"CSD DESIGN");
lv_obj_set_style_text_font(ui_CSD2, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Active_Screen, ui_event_Active_Screen, LV_EVENT_ALL, NULL);

}
