// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Killin-IT_TEST

#include "../ui.h"

void ui_Clear_Screen_screen_init(void)
{
ui_Clear_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Clear_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Clear_Arc = lv_arc_create(ui_Clear_Screen);
lv_obj_set_width( ui_Clear_Arc, 240);
lv_obj_set_height( ui_Clear_Arc, 240);
lv_obj_set_align( ui_Clear_Arc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Clear_Arc, 1);
lv_arc_set_bg_angles(ui_Clear_Arc,150,30);
lv_obj_set_style_arc_color(ui_Clear_Arc, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Clear_Arc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Clear_Arc, 24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Clear_Arc, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Clear_Arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Clear_Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Clear_Arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Clear5 = lv_label_create(ui_Clear_Screen);
lv_obj_set_width( ui_Clear5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Clear5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Clear5, -1 );
lv_obj_set_y( ui_Clear5, 70 );
lv_obj_set_align( ui_Clear5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Clear5,"CLEAR");
lv_obj_set_style_text_color(ui_Clear5, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Clear5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Clear5, &ui_font_Designer, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Clear_Screen);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -1 );
lv_obj_set_y( ui_Label2, -20 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"KILLIN'-IT");
lv_obj_set_style_text_font(ui_Label2, &ui_font_Akira_Extended, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Clear_Screen);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -1 );
lv_obj_set_y( ui_Label3, 10 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"E-STOP SYSTEM");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CSD = lv_label_create(ui_Clear_Screen);
lv_obj_set_width( ui_CSD, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CSD, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CSD, 0 );
lv_obj_set_y( ui_CSD, 110 );
lv_obj_set_align( ui_CSD, LV_ALIGN_CENTER );
lv_label_set_text(ui_CSD,"CSD DESIGN");
lv_obj_set_style_text_font(ui_CSD, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Clear_Arc, ui_event_Clear_Arc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Clear_Screen, ui_event_Clear_Screen, LV_EVENT_ALL, NULL);

}
