// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Killin-IT_TEST

#include "../ui.h"

void ui_No_Connection_Clear_screen_init(void)
{
ui_No_Connection_Clear = lv_obj_create(NULL);
lv_obj_clear_flag( ui_No_Connection_Clear, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_No_Conn_Clear_Arc = lv_arc_create(ui_No_Connection_Clear);
lv_obj_set_width( ui_No_Conn_Clear_Arc, 240);
lv_obj_set_height( ui_No_Conn_Clear_Arc, 240);
lv_obj_set_align( ui_No_Conn_Clear_Arc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_No_Conn_Clear_Arc, 1);
lv_arc_set_bg_angles(ui_No_Conn_Clear_Arc,150,30);
lv_obj_set_style_arc_color(ui_No_Conn_Clear_Arc, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_No_Conn_Clear_Arc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_No_Conn_Clear_Arc, 24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_No_Conn_Clear_Arc, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_No_Conn_Clear_Arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_No_Conn_Clear_Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_No_Conn_Clear_Arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_No_Network_Clear = lv_label_create(ui_No_Connection_Clear);
lv_obj_set_width( ui_No_Network_Clear, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_No_Network_Clear, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_No_Network_Clear, -1 );
lv_obj_set_y( ui_No_Network_Clear, 61 );
lv_obj_set_align( ui_No_Network_Clear, LV_ALIGN_CENTER );
lv_label_set_text(ui_No_Network_Clear,"No\nNetwork");
lv_obj_set_style_text_color(ui_No_Network_Clear, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_No_Network_Clear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_No_Network_Clear, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_No_Network_Clear, &ui_font_Designer24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_No_Connection_Clear);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -1 );
lv_obj_set_y( ui_Label10, -20 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"KILLIN'-IT");
lv_obj_set_style_text_font(ui_Label10, &ui_font_Akira_Extended, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_No_Connection_Clear);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -1 );
lv_obj_set_y( ui_Label11, 10 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"E-STOP SYSTEM");
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_No_Connection_Clear);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, 0 );
lv_obj_set_y( ui_Label12, 110 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"CSD DESIGN");
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Clear_No_Network_Tag = lv_label_create(ui_No_Connection_Clear);
lv_obj_set_width( ui_Clear_No_Network_Tag, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Clear_No_Network_Tag, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Clear_No_Network_Tag, -1 );
lv_obj_set_y( ui_Clear_No_Network_Tag, -55 );
lv_obj_set_align( ui_Clear_No_Network_Tag, LV_ALIGN_CENTER );
lv_label_set_text(ui_Clear_No_Network_Tag,"CLEAR");
lv_obj_set_style_text_color(ui_Clear_No_Network_Tag, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Clear_No_Network_Tag, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Clear_No_Network_Tag, &ui_font_Designer24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_No_Connection_Clear, ui_event_No_Connection_Clear, LV_EVENT_ALL, NULL);

}
