// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Killin-IT_TEST

#include "../ui.h"

void ui_Standby_Screen_screen_init(void)
{
ui_Standby_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Standby_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Standby_Arc = lv_arc_create(ui_Standby_Screen);
lv_obj_set_width( ui_Standby_Arc, 240);
lv_obj_set_height( ui_Standby_Arc, 240);
lv_obj_set_align( ui_Standby_Arc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Standby_Arc, 1);
lv_arc_set_bg_angles(ui_Standby_Arc,150,30);
lv_obj_set_style_arc_color(ui_Standby_Arc, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Standby_Arc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Standby_Arc, 24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Standby_Arc, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Standby_Arc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Standby_Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Standby_Arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Standby = lv_label_create(ui_Standby_Screen);
lv_obj_set_width( ui_Standby, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Standby, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Standby, -1 );
lv_obj_set_y( ui_Standby, 74 );
lv_obj_set_align( ui_Standby, LV_ALIGN_CENTER );
lv_label_set_text(ui_Standby,"STANDBY");
lv_obj_set_style_text_color(ui_Standby, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Standby, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Standby, &ui_font_Designer24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Standby_Screen);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -1 );
lv_obj_set_y( ui_Label7, -20 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"KILLIN'-IT");
lv_obj_set_style_text_font(ui_Label7, &ui_font_Akira_Extended, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Standby_Screen);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -1 );
lv_obj_set_y( ui_Label8, 10 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"E-STOP SYSTEM");
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Standby_Screen);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 0 );
lv_obj_set_y( ui_Label9, 110 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"CSD DESIGN");
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Standby_Screen, ui_event_Standby_Screen, LV_EVENT_ALL, NULL);

}
