// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Killin-IT_TEST

#ifndef _UI_COMP_CLEAR_H
#define _UI_COMP_CLEAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Clear
#define UI_COMP_CLEAR_CLEAR 0
#define _UI_COMP_CLEAR_NUM 1
lv_obj_t *ui_Clear_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
