// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Killin-IT_TEST

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void SmoothDown_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Clear_Screen
void ui_Clear_Screen_screen_init(void);
void ui_event_Clear_Screen( lv_event_t * e);
lv_obj_t *ui_Clear_Screen;
void ui_event_Clear_Arc( lv_event_t * e);
lv_obj_t *ui_Clear_Arc;
lv_obj_t *ui_Clear5;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_CSD;


// SCREEN: ui_Active_Screen
void ui_Active_Screen_screen_init(void);
void ui_event_Active_Screen( lv_event_t * e);
lv_obj_t *ui_Active_Screen;
lv_obj_t *ui_Active_Arc;
lv_obj_t *ui_Active;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label5;
lv_obj_t *ui_CSD2;


// SCREEN: ui_Standby_Screen
void ui_Standby_Screen_screen_init(void);
void ui_event_Standby_Screen( lv_event_t * e);
lv_obj_t *ui_Standby_Screen;
lv_obj_t *ui_Standby_Arc;
lv_obj_t *ui_Standby;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Label9;


// SCREEN: ui_No_Connection_Clear
void ui_No_Connection_Clear_screen_init(void);
void ui_event_No_Connection_Clear( lv_event_t * e);
lv_obj_t *ui_No_Connection_Clear;
lv_obj_t *ui_No_Conn_Clear_Arc;
lv_obj_t *ui_No_Network_Clear;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Clear_No_Network_Tag;


// SCREEN: ui_No_Connection_Active
void ui_No_Connection_Active_screen_init(void);
void ui_event_No_Connection_Active( lv_event_t * e);
lv_obj_t *ui_No_Connection_Active;
lv_obj_t *ui_No_Conn_Active_Arc;
lv_obj_t *ui_No_Network_Active;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Active_No_Network_Tag;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void SmoothDown_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 750);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_1, -240, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Clear_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      SmoothDown_Animation(ui_Clear_Screen, 0);
      call_clear_screen( e );
}
}
void ui_event_Clear_Arc( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      SmoothDown_Animation(ui_Clear_Screen, 0);
}
}
void ui_event_Active_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      SmoothDown_Animation(ui_Active_Screen, 0);
      call_active_screen( e );
}
}
void ui_event_Standby_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      SmoothDown_Animation(ui_Standby_Screen, 0);
      call_standby_screen( e );
}
}
void ui_event_No_Connection_Clear( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      SmoothDown_Animation(ui_No_Connection_Clear, 0);
      call_noconn_clear( e );
}
}
void ui_event_No_Connection_Active( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      SmoothDown_Animation(ui_No_Connection_Active, 0);
      call_noconn_active( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Clear_Screen_screen_init();
ui_Active_Screen_screen_init();
ui_Standby_Screen_screen_init();
ui_No_Connection_Clear_screen_init();
ui_No_Connection_Active_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Clear_Screen);
}
