// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Killin-IT_TEST

#ifndef _KILLIN_IT_TEST_UI_H
#define _KILLIN_IT_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
void SmoothDown_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Clear_Screen
void ui_Clear_Screen_screen_init(void);
void ui_event_Clear_Screen( lv_event_t * e);
extern lv_obj_t *ui_Clear_Screen;
void ui_event_Clear_Arc( lv_event_t * e);
extern lv_obj_t *ui_Clear_Arc;
extern lv_obj_t *ui_Clear5;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_CSD;
// SCREEN: ui_Active_Screen
void ui_Active_Screen_screen_init(void);
void ui_event_Active_Screen( lv_event_t * e);
extern lv_obj_t *ui_Active_Screen;
extern lv_obj_t *ui_Active_Arc;
extern lv_obj_t *ui_Active;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_CSD2;
// SCREEN: ui_Standby_Screen
void ui_Standby_Screen_screen_init(void);
void ui_event_Standby_Screen( lv_event_t * e);
extern lv_obj_t *ui_Standby_Screen;
extern lv_obj_t *ui_Standby_Arc;
extern lv_obj_t *ui_Standby;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
// SCREEN: ui_No_Connection_Clear
void ui_No_Connection_Clear_screen_init(void);
void ui_event_No_Connection_Clear( lv_event_t * e);
extern lv_obj_t *ui_No_Connection_Clear;
extern lv_obj_t *ui_No_Conn_Clear_Arc;
extern lv_obj_t *ui_No_Network_Clear;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Clear_No_Network_Tag;
// SCREEN: ui_No_Connection_Active
void ui_No_Connection_Active_screen_init(void);
void ui_event_No_Connection_Active( lv_event_t * e);
extern lv_obj_t *ui_No_Connection_Active;
extern lv_obj_t *ui_No_Conn_Active_Arc;
extern lv_obj_t *ui_No_Network_Active;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Active_No_Network_Tag;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_Akira_Extended);
LV_FONT_DECLARE( ui_font_Designer);
LV_FONT_DECLARE( ui_font_Designer24);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
