// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Killin-IT_TEST

#include "ui.h"

void call_clear_screen(lv_event_t * e)
{
	// Your code here
}

void call_active_screen(lv_event_t * e)
{
	// Your code here
}

void call_standby_screen(lv_event_t * e)
{
	// Your code here
}

void call_noconn_clear(lv_event_t * e)
{
	// Your code here
}

void call_noconn_active(lv_event_t * e)
{
	// Your code here
}
